{% set name = "lbmpy" %}
{% set version = "1.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mabau/lbmpy/archive/release/{{ version }}.tar.gz
  sha256: ce0ce974b0a8c2e751472c2d4df2533a71a1f3dfdb87efdb814c23d6061bc2b1

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython
  run:
    - numpy >=1.11.0
    - pystencils >=1.0
    - python
    - sympy >=1.2

test:
  imports:
    - lbmpy
    - lbmpy.advanced_streaming
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://i10git.cs.fau.de/pycodegen/lbmpy/
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.txt
  summary: Code Generation for Lattice Boltzmann Methods
  description: |
    Run fast fluid simulations based on the lattice Boltzmann method
    in Python on CPUs and GPUs. lbmpy creates highly optimized LB compute
    kernels in C or CUDA, for a wide variety of different collision
    operators, including MRT, entropic, and cumulant schemes.
  doc_url: https://i10git.cs.fau.de/pycodegen/lbmpy/
  dev_url: https://i10git.cs.fau.de/pycodegen/lbmpy/

extra:
  recipe-maintainers:
    - jan-janssen
