{% set name = "lbmpy" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lbmpy-{{ version }}.tar.gz
  sha256: 4000455c3aa9f1ef73b626ef83da436f29c8f758048b5f33ea3e01f36b6de024

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - numpy >=1.11.0
    - pystencils
    - python
    - sympy >=1.2

test:
  imports:
    - lbmpy
    - lbmpy.advanced_streaming
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://i10git.cs.fau.de/pycodegen/lbmpy/
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.txt
  summary: Code Generation for Lattice Boltzmann Methods
  description: |
    Run fast fluid simulations based on the lattice Boltzmann method
    in Python on CPUs and GPUs. lbmpy creates highly optimized LB compute
    kernels in C or CUDA, for a wide variety of different collision
    operators, including MRT, entropic, and cumulant schemes.
  doc_url: https://i10git.cs.fau.de/pycodegen/lbmpy/
  dev_url: https://i10git.cs.fau.de/pycodegen/lbmpy/

extra:
  recipe-maintainers:
    - jan-janssen
